//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:49:52 PM SAST 
//


package com.inted.as.hss.fe.cx.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.inted.as.hss.fe.models.cx package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IMSSubscription_QNAME = new QName("", "IMSSubscription");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.inted.as.hss.fe.models.cx
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TIMSSubscription }
     * 
     */
    public TIMSSubscription createTIMSSubscription() {
        return new TIMSSubscription();
    }

    /**
     * Create an instance of {@link TSePoTri }
     * 
     */
    public TSePoTri createTSePoTri() {
        return new TSePoTri();
    }

    /**
     * Create an instance of {@link TReferenceLocationInformation }
     * 
     */
    public TReferenceLocationInformation createTReferenceLocationInformation() {
        return new TReferenceLocationInformation();
    }

    /**
     * Create an instance of {@link TSePoTriExtension }
     * 
     */
    public TSePoTriExtension createTSePoTriExtension() {
        return new TSePoTriExtension();
    }

    /**
     * Create an instance of {@link TIMSSubscriptionExtension }
     * 
     */
    public TIMSSubscriptionExtension createTIMSSubscriptionExtension() {
        return new TIMSSubscriptionExtension();
    }

    /**
     * Create an instance of {@link TApplicationServer }
     * 
     */
    public TApplicationServer createTApplicationServer() {
        return new TApplicationServer();
    }

    /**
     * Create an instance of {@link TIMSSubscriptionExtension2 }
     * 
     */
    public TIMSSubscriptionExtension2 createTIMSSubscriptionExtension2() {
        return new TIMSSubscriptionExtension2();
    }

    /**
     * Create an instance of {@link TSessionDescription }
     * 
     */
    public TSessionDescription createTSessionDescription() {
        return new TSessionDescription();
    }

    /**
     * Create an instance of {@link TServiceProfile }
     * 
     */
    public TServiceProfile createTServiceProfile() {
        return new TServiceProfile();
    }

    /**
     * Create an instance of {@link TExtendedPriority }
     * 
     */
    public TExtendedPriority createTExtendedPriority() {
        return new TExtendedPriority();
    }

    /**
     * Create an instance of {@link TCoreNetworkServicesAuthorization }
     * 
     */
    public TCoreNetworkServicesAuthorization createTCoreNetworkServicesAuthorization() {
        return new TCoreNetworkServicesAuthorization();
    }

    /**
     * Create an instance of {@link TExtension }
     * 
     */
    public TExtension createTExtension() {
        return new TExtension();
    }

    /**
     * Create an instance of {@link TPublicIdentityExtension3 }
     * 
     */
    public TPublicIdentityExtension3 createTPublicIdentityExtension3() {
        return new TPublicIdentityExtension3();
    }

    /**
     * Create an instance of {@link TPublicIdentityExtension2 }
     * 
     */
    public TPublicIdentityExtension2 createTPublicIdentityExtension2() {
        return new TPublicIdentityExtension2();
    }

    /**
     * Create an instance of {@link TInitialFilterCriteria }
     * 
     */
    public TInitialFilterCriteria createTInitialFilterCriteria() {
        return new TInitialFilterCriteria();
    }

    /**
     * Create an instance of {@link TServiceProfileExtension }
     * 
     */
    public TServiceProfileExtension createTServiceProfileExtension() {
        return new TServiceProfileExtension();
    }

    /**
     * Create an instance of {@link THeader }
     * 
     */
    public THeader createTHeader() {
        return new THeader();
    }

    /**
     * Create an instance of {@link TPublicIdentityExtension4 }
     * 
     */
    public TPublicIdentityExtension4 createTPublicIdentityExtension4() {
        return new TPublicIdentityExtension4();
    }

    /**
     * Create an instance of {@link TPublicIdentityExtension5 }
     * 
     */
    public TPublicIdentityExtension5 createTPublicIdentityExtension5() {
        return new TPublicIdentityExtension5();
    }

    /**
     * Create an instance of {@link TApplicationServerExtension }
     * 
     */
    public TApplicationServerExtension createTApplicationServerExtension() {
        return new TApplicationServerExtension();
    }

    /**
     * Create an instance of {@link TTrigger }
     * 
     */
    public TTrigger createTTrigger() {
        return new TTrigger();
    }

    /**
     * Create an instance of {@link TIncludeRegisterRequest }
     * 
     */
    public TIncludeRegisterRequest createTIncludeRegisterRequest() {
        return new TIncludeRegisterRequest();
    }

    /**
     * Create an instance of {@link TPublicIdentityExtension }
     * 
     */
    public TPublicIdentityExtension createTPublicIdentityExtension() {
        return new TPublicIdentityExtension();
    }

    /**
     * Create an instance of {@link TIncludeRegisterResponse }
     * 
     */
    public TIncludeRegisterResponse createTIncludeRegisterResponse() {
        return new TIncludeRegisterResponse();
    }

    /**
     * Create an instance of {@link TListOfServiceIds }
     * 
     */
    public TListOfServiceIds createTListOfServiceIds() {
        return new TListOfServiceIds();
    }

    /**
     * Create an instance of {@link TCNServicesAuthorizationExtension }
     * 
     */
    public TCNServicesAuthorizationExtension createTCNServicesAuthorizationExtension() {
        return new TCNServicesAuthorizationExtension();
    }

    /**
     * Create an instance of {@link TPublicIdentity }
     * 
     */
    public TPublicIdentity createTPublicIdentity() {
        return new TPublicIdentity();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIMSSubscription }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IMSSubscription")
    public JAXBElement<TIMSSubscription> createIMSSubscription(TIMSSubscription value) {
        return new JAXBElement<TIMSSubscription>(_IMSSubscription_QNAME, TIMSSubscription.class, null, value);
    }

}
