//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:49:52 PM SAST 
//


package com.inted.as.hss.fe.cx.models;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;


/**
 * <p>Java class for tApplicationServerExtension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tApplicationServerExtension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncludeRegisterRequest" type="{}tIncludeRegisterRequest" minOccurs="0"/>
 *         &lt;element name="IncludeRegisterResponse" type="{}tIncludeRegisterResponse" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tExtension" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tApplicationServerExtension", propOrder = {
    "includeRegisterRequest",
    "includeRegisterResponse",
    "extension",
    "any"
})
public class TApplicationServerExtension {

    @XmlElement(name = "IncludeRegisterRequest")
    protected TIncludeRegisterRequest includeRegisterRequest;
    @XmlElement(name = "IncludeRegisterResponse")
    protected TIncludeRegisterResponse includeRegisterResponse;
    @XmlElement(name = "Extension")
    protected TExtension extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the includeRegisterRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TIncludeRegisterRequest }
     *     
     */
    public TIncludeRegisterRequest getIncludeRegisterRequest() {
        return includeRegisterRequest;
    }

    /**
     * Sets the value of the includeRegisterRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIncludeRegisterRequest }
     *     
     */
    public void setIncludeRegisterRequest(TIncludeRegisterRequest value) {
        this.includeRegisterRequest = value;
    }

    /**
     * Gets the value of the includeRegisterResponse property.
     * 
     * @return
     *     possible object is
     *     {@link TIncludeRegisterResponse }
     *     
     */
    public TIncludeRegisterResponse getIncludeRegisterResponse() {
        return includeRegisterResponse;
    }

    /**
     * Sets the value of the includeRegisterResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIncludeRegisterResponse }
     *     
     */
    public void setIncludeRegisterResponse(TIncludeRegisterResponse value) {
        this.includeRegisterResponse = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TExtension }
     *     
     */
    public TExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExtension }
     *     
     */
    public void setExtension(TExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
