//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:49:52 PM SAST 
//


package com.inted.as.hss.fe.cx.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tCNServicesAuthorizationExtension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCNServicesAuthorizationExtension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListOfServiceIds" type="{}tListOfServiceIds" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCNServicesAuthorizationExtension", propOrder = {
    "listOfServiceIds",
    "extension"
})
public class TCNServicesAuthorizationExtension {

    @XmlElement(name = "ListOfServiceIds")
    protected TListOfServiceIds listOfServiceIds;
    @XmlElement(name = "Extension")
    protected TExtension extension;

    /**
     * Gets the value of the listOfServiceIds property.
     * 
     * @return
     *     possible object is
     *     {@link TListOfServiceIds }
     *     
     */
    public TListOfServiceIds getListOfServiceIds() {
        return listOfServiceIds;
    }

    /**
     * Sets the value of the listOfServiceIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link TListOfServiceIds }
     *     
     */
    public void setListOfServiceIds(TListOfServiceIds value) {
        this.listOfServiceIds = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TExtension }
     *     
     */
    public TExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExtension }
     *     
     */
    public void setExtension(TExtension value) {
        this.extension = value;
    }

}
