//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:49:52 PM SAST 
//


package com.inted.as.hss.fe.cx.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tPublicIdentityExtension3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPublicIdentityExtension3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WildcardedIMPU" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="ServiceLevelTraceInfo" type="{}tServiceLevelTraceInfo" minOccurs="0"/>
 *         &lt;element name="ServicePriorityLevel" type="{}tServicePriorityLevel" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tPublicIdentityExtension4" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPublicIdentityExtension3", propOrder = {
    "wildcardedIMPU",
    "serviceLevelTraceInfo",
    "servicePriorityLevel",
    "extension"
})
public class TPublicIdentityExtension3 {

    @XmlElement(name = "WildcardedIMPU")
    @XmlSchemaType(name = "anyURI")
    protected String wildcardedIMPU;
    @XmlElement(name = "ServiceLevelTraceInfo")
    protected String serviceLevelTraceInfo;
    @XmlElement(name = "ServicePriorityLevel")
    protected Short servicePriorityLevel;
    @XmlElement(name = "Extension")
    protected TPublicIdentityExtension4 extension;

    /**
     * Gets the value of the wildcardedIMPU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWildcardedIMPU() {
        return wildcardedIMPU;
    }

    /**
     * Sets the value of the wildcardedIMPU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWildcardedIMPU(String value) {
        this.wildcardedIMPU = value;
    }

    /**
     * Gets the value of the serviceLevelTraceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLevelTraceInfo() {
        return serviceLevelTraceInfo;
    }

    /**
     * Sets the value of the serviceLevelTraceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLevelTraceInfo(String value) {
        this.serviceLevelTraceInfo = value;
    }

    /**
     * Gets the value of the servicePriorityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getServicePriorityLevel() {
        return servicePriorityLevel;
    }

    /**
     * Sets the value of the servicePriorityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setServicePriorityLevel(Short value) {
        this.servicePriorityLevel = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TPublicIdentityExtension4 }
     *     
     */
    public TPublicIdentityExtension4 getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublicIdentityExtension4 }
     *     
     */
    public void setExtension(TPublicIdentityExtension4 value) {
        this.extension = value;
    }

}
