//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:49:52 PM SAST 
//


package com.inted.as.hss.fe.cx.models;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;


/**
 * <p>Java class for tServiceProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tServiceProfile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PublicIdentity" type="{}tPublicIdentity" maxOccurs="unbounded"/>
 *         &lt;element name="CoreNetworkServicesAuthorization" type="{}tCoreNetworkServicesAuthorization" minOccurs="0"/>
 *         &lt;element name="InitialFilterCriteria" type="{}tInitialFilterCriteria" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tServiceProfileExtension" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tServiceProfile", propOrder = {
    "publicIdentity",
    "coreNetworkServicesAuthorization",
    "initialFilterCriteria",
    "extension",
    "any"
})
public class TServiceProfile {

    @XmlElement(name = "PublicIdentity", required = true)
    protected List<TPublicIdentity> publicIdentity;
    @XmlElement(name = "CoreNetworkServicesAuthorization")
    protected TCoreNetworkServicesAuthorization coreNetworkServicesAuthorization;
    @XmlElement(name = "InitialFilterCriteria")
    protected List<TInitialFilterCriteria> initialFilterCriteria;
    @XmlElement(name = "Extension")
    protected TServiceProfileExtension extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the publicIdentity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publicIdentity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublicIdentity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TPublicIdentity }
     * 
     * 
     */
    public List<TPublicIdentity> getPublicIdentity() {
        if (publicIdentity == null) {
            publicIdentity = new ArrayList<TPublicIdentity>();
        }
        return this.publicIdentity;
    }

    /**
     * Gets the value of the coreNetworkServicesAuthorization property.
     * 
     * @return
     *     possible object is
     *     {@link TCoreNetworkServicesAuthorization }
     *     
     */
    public TCoreNetworkServicesAuthorization getCoreNetworkServicesAuthorization() {
        return coreNetworkServicesAuthorization;
    }

    /**
     * Sets the value of the coreNetworkServicesAuthorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCoreNetworkServicesAuthorization }
     *     
     */
    public void setCoreNetworkServicesAuthorization(TCoreNetworkServicesAuthorization value) {
        this.coreNetworkServicesAuthorization = value;
    }

    /**
     * Gets the value of the initialFilterCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initialFilterCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitialFilterCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInitialFilterCriteria }
     * 
     * 
     */
    public List<TInitialFilterCriteria> getInitialFilterCriteria() {
        if (initialFilterCriteria == null) {
            initialFilterCriteria = new ArrayList<TInitialFilterCriteria>();
        }
        return this.initialFilterCriteria;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceProfileExtension }
     *     
     */
    public TServiceProfileExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceProfileExtension }
     *     
     */
    public void setExtension(TServiceProfileExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
