//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.inted.as.hss.fe.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ShData_QNAME = new QName("", "Sh-Data");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.inted.as.hss.fe.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TShData }
     * 
     */
    public TShData createTShData() {
        return new TShData();
    }

    /**
     * Create an instance of {@link TCSLocationInformationExtension2 }
     * 
     */
    public TCSLocationInformationExtension2 createTCSLocationInformationExtension2() {
        return new TCSLocationInformationExtension2();
    }

    /**
     * Create an instance of {@link TSePoTriExtension }
     * 
     */
    public TSePoTriExtension createTSePoTriExtension() {
        return new TSePoTriExtension();
    }

    /**
     * Create an instance of {@link TApplicationServer }
     * 
     */
    public TApplicationServer createTApplicationServer() {
        return new TApplicationServer();
    }

    /**
     * Create an instance of {@link TIFCs }
     * 
     */
    public TIFCs createTIFCs() {
        return new TIFCs();
    }

    /**
     * Create an instance of {@link TDSAI }
     * 
     */
    public TDSAI createTDSAI() {
        return new TDSAI();
    }

    /**
     * Create an instance of {@link TSMSRegistrationInfo }
     * 
     */
    public TSMSRegistrationInfo createTSMSRegistrationInfo() {
        return new TSMSRegistrationInfo();
    }

    /**
     * Create an instance of {@link TSessionDescription }
     * 
     */
    public TSessionDescription createTSessionDescription() {
        return new TSessionDescription();
    }

    /**
     * Create an instance of {@link TISDNAddress }
     * 
     */
    public TISDNAddress createTISDNAddress() {
        return new TISDNAddress();
    }

    /**
     * Create an instance of {@link TPublicIdentityExtension3 }
     * 
     */
    public TPublicIdentityExtension3 createTPublicIdentityExtension3() {
        return new TPublicIdentityExtension3();
    }

    /**
     * Create an instance of {@link TInitialFilterCriteria }
     * 
     */
    public TInitialFilterCriteria createTInitialFilterCriteria() {
        return new TInitialFilterCriteria();
    }

    /**
     * Create an instance of {@link TPublicIdentityExtension2 }
     * 
     */
    public TPublicIdentityExtension2 createTPublicIdentityExtension2() {
        return new TPublicIdentityExtension2();
    }

    /**
     * Create an instance of {@link THeader }
     * 
     */
    public THeader createTHeader() {
        return new THeader();
    }

    /**
     * Create an instance of {@link TShIMSDataExtension }
     * 
     */
    public TShIMSDataExtension createTShIMSDataExtension() {
        return new TShIMSDataExtension();
    }

    /**
     * Create an instance of {@link TIncludeRegisterRequest }
     * 
     */
    public TIncludeRegisterRequest createTIncludeRegisterRequest() {
        return new TIncludeRegisterRequest();
    }

    /**
     * Create an instance of {@link TLocalTimeZone }
     * 
     */
    public TLocalTimeZone createTLocalTimeZone() {
        return new TLocalTimeZone();
    }

    /**
     * Create an instance of {@link TChargingInformation }
     * 
     */
    public TChargingInformation createTChargingInformation() {
        return new TChargingInformation();
    }

    /**
     * Create an instance of {@link TPublicIdentityExtension }
     * 
     */
    public TPublicIdentityExtension createTPublicIdentityExtension() {
        return new TPublicIdentityExtension();
    }

    /**
     * Create an instance of {@link TShDataExtension2 }
     * 
     */
    public TShDataExtension2 createTShDataExtension2() {
        return new TShDataExtension2();
    }

    /**
     * Create an instance of {@link TShDataExtension3 }
     * 
     */
    public TShDataExtension3 createTShDataExtension3() {
        return new TShDataExtension3();
    }

    /**
     * Create an instance of {@link TIncludeRegisterResponse }
     * 
     */
    public TIncludeRegisterResponse createTIncludeRegisterResponse() {
        return new TIncludeRegisterResponse();
    }

    /**
     * Create an instance of {@link TShDataExtension4 }
     * 
     */
    public TShDataExtension4 createTShDataExtension4() {
        return new TShDataExtension4();
    }

    /**
     * Create an instance of {@link TShDataExtension5 }
     * 
     */
    public TShDataExtension5 createTShDataExtension5() {
        return new TShDataExtension5();
    }

    /**
     * Create an instance of {@link TTransparentData }
     * 
     */
    public TTransparentData createTTransparentData() {
        return new TTransparentData();
    }

    /**
     * Create an instance of {@link TShIMSData }
     * 
     */
    public TShIMSData createTShIMSData() {
        return new TShIMSData();
    }

    /**
     * Create an instance of {@link TUserCSGInformation }
     * 
     */
    public TUserCSGInformation createTUserCSGInformation() {
        return new TUserCSGInformation();
    }

    /**
     * Create an instance of {@link TServiceData }
     * 
     */
    public TServiceData createTServiceData() {
        return new TServiceData();
    }

    /**
     * Create an instance of {@link TSePoTri }
     * 
     */
    public TSePoTri createTSePoTri() {
        return new TSePoTri();
    }

    /**
     * Create an instance of {@link TReferenceLocationInformation }
     * 
     */
    public TReferenceLocationInformation createTReferenceLocationInformation() {
        return new TReferenceLocationInformation();
    }

    /**
     * Create an instance of {@link TExtendedPriority }
     * 
     */
    public TExtendedPriority createTExtendedPriority() {
        return new TExtendedPriority();
    }

    /**
     * Create an instance of {@link TExtendedMSISDN }
     * 
     */
    public TExtendedMSISDN createTExtendedMSISDN() {
        return new TExtendedMSISDN();
    }

    /**
     * Create an instance of {@link TPSLocationInformationExtension }
     * 
     */
    public TPSLocationInformationExtension createTPSLocationInformationExtension() {
        return new TPSLocationInformationExtension();
    }

    /**
     * Create an instance of {@link TEPSLocationInformation }
     * 
     */
    public TEPSLocationInformation createTEPSLocationInformation() {
        return new TEPSLocationInformation();
    }

    /**
     * Create an instance of {@link TExtension }
     * 
     */
    public TExtension createTExtension() {
        return new TExtension();
    }

    /**
     * Create an instance of {@link TTADSinformationExtension }
     * 
     */
    public TTADSinformationExtension createTTADSinformationExtension() {
        return new TTADSinformationExtension();
    }

    /**
     * Create an instance of {@link TShIMSDataExtension3 }
     * 
     */
    public TShIMSDataExtension3 createTShIMSDataExtension3() {
        return new TShIMSDataExtension3();
    }

    /**
     * Create an instance of {@link TShIMSDataExtension4 }
     * 
     */
    public TShIMSDataExtension4 createTShIMSDataExtension4() {
        return new TShIMSDataExtension4();
    }

    /**
     * Create an instance of {@link TShIMSDataExtension5 }
     * 
     */
    public TShIMSDataExtension5 createTShIMSDataExtension5() {
        return new TShIMSDataExtension5();
    }

    /**
     * Create an instance of {@link TShIMSDataExtension6 }
     * 
     */
    public TShIMSDataExtension6 createTShIMSDataExtension6() {
        return new TShIMSDataExtension6();
    }

    /**
     * Create an instance of {@link TShIMSDataExtension2 }
     * 
     */
    public TShIMSDataExtension2 createTShIMSDataExtension2() {
        return new TShIMSDataExtension2();
    }

    /**
     * Create an instance of {@link TTADSinformation }
     * 
     */
    public TTADSinformation createTTADSinformation() {
        return new TTADSinformation();
    }

    /**
     * Create an instance of {@link TApplicationServerExtension }
     * 
     */
    public TApplicationServerExtension createTApplicationServerExtension() {
        return new TApplicationServerExtension();
    }

    /**
     * Create an instance of {@link TTrigger }
     * 
     */
    public TTrigger createTTrigger() {
        return new TTrigger();
    }

    /**
     * Create an instance of {@link TUEReachabilityForIP }
     * 
     */
    public TUEReachabilityForIP createTUEReachabilityForIP() {
        return new TUEReachabilityForIP();
    }

    /**
     * Create an instance of {@link TPSLocationInformationExtension2 }
     * 
     */
    public TPSLocationInformationExtension2 createTPSLocationInformationExtension2() {
        return new TPSLocationInformationExtension2();
    }

    /**
     * Create an instance of {@link TUEReachabilityForIPExtension }
     * 
     */
    public TUEReachabilityForIPExtension createTUEReachabilityForIPExtension() {
        return new TUEReachabilityForIPExtension();
    }

    /**
     * Create an instance of {@link TEPSLocationInformationExtension }
     * 
     */
    public TEPSLocationInformationExtension createTEPSLocationInformationExtension() {
        return new TEPSLocationInformationExtension();
    }

    /**
     * Create an instance of {@link TShDataExtension }
     * 
     */
    public TShDataExtension createTShDataExtension() {
        return new TShDataExtension();
    }

    /**
     * Create an instance of {@link TUserCSGInformationExtension }
     * 
     */
    public TUserCSGInformationExtension createTUserCSGInformationExtension() {
        return new TUserCSGInformationExtension();
    }

    /**
     * Create an instance of {@link TCSLocationInformationExtension }
     * 
     */
    public TCSLocationInformationExtension createTCSLocationInformationExtension() {
        return new TCSLocationInformationExtension();
    }

    /**
     * Create an instance of {@link TCSLocationInformation }
     * 
     */
    public TCSLocationInformation createTCSLocationInformation() {
        return new TCSLocationInformation();
    }

    /**
     * Create an instance of {@link TSMSRegistrationInfoExtension }
     * 
     */
    public TSMSRegistrationInfoExtension createTSMSRegistrationInfoExtension() {
        return new TSMSRegistrationInfoExtension();
    }

    /**
     * Create an instance of {@link TPSLocationInformation }
     * 
     */
    public TPSLocationInformation createTPSLocationInformation() {
        return new TPSLocationInformation();
    }

    /**
     * Create an instance of {@link TPublicIdentity }
     * 
     */
    public TPublicIdentity createTPublicIdentity() {
        return new TPublicIdentity();
    }

    /**
     * Create an instance of {@link TTWANLocationInformation }
     * 
     */
    public TTWANLocationInformation createTTWANLocationInformation() {
        return new TTWANLocationInformation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TShData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sh-Data")
    public JAXBElement<TShData> createShData(TShData value) {
        return new JAXBElement<TShData>(_ShData_QNAME, TShData.class, null, value);
    }

}
