//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for tChargingInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tChargingInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrimaryEventChargingFunctionName" type="{}tDiameterURI" minOccurs="0"/>
 *         &lt;element name="SecondaryEventChargingFunctionName" type="{}tDiameterURI" minOccurs="0"/>
 *         &lt;element name="PrimaryChargingCollectionFunctionName" type="{}tDiameterURI" minOccurs="0"/>
 *         &lt;element name="SecondaryChargingCollectionFunctionName" type="{}tDiameterURI" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tExtension" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tChargingInformation", propOrder = {
    "primaryEventChargingFunctionName",
    "secondaryEventChargingFunctionName",
    "primaryChargingCollectionFunctionName",
    "secondaryChargingCollectionFunctionName",
    "extension",
    "any"
})
public class TChargingInformation {

    @XmlElement(name = "PrimaryEventChargingFunctionName")
    protected String primaryEventChargingFunctionName;
    @XmlElement(name = "SecondaryEventChargingFunctionName")
    protected String secondaryEventChargingFunctionName;
    @XmlElement(name = "PrimaryChargingCollectionFunctionName")
    protected String primaryChargingCollectionFunctionName;
    @XmlElement(name = "SecondaryChargingCollectionFunctionName")
    protected String secondaryChargingCollectionFunctionName;
    @XmlElement(name = "Extension")
    protected TExtension extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the primaryEventChargingFunctionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryEventChargingFunctionName() {
        return primaryEventChargingFunctionName;
    }

    /**
     * Sets the value of the primaryEventChargingFunctionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryEventChargingFunctionName(String value) {
        this.primaryEventChargingFunctionName = value;
    }

    /**
     * Gets the value of the secondaryEventChargingFunctionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryEventChargingFunctionName() {
        return secondaryEventChargingFunctionName;
    }

    /**
     * Sets the value of the secondaryEventChargingFunctionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryEventChargingFunctionName(String value) {
        this.secondaryEventChargingFunctionName = value;
    }

    /**
     * Gets the value of the primaryChargingCollectionFunctionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryChargingCollectionFunctionName() {
        return primaryChargingCollectionFunctionName;
    }

    /**
     * Sets the value of the primaryChargingCollectionFunctionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryChargingCollectionFunctionName(String value) {
        this.primaryChargingCollectionFunctionName = value;
    }

    /**
     * Gets the value of the secondaryChargingCollectionFunctionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryChargingCollectionFunctionName() {
        return secondaryChargingCollectionFunctionName;
    }

    /**
     * Sets the value of the secondaryChargingCollectionFunctionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryChargingCollectionFunctionName(String value) {
        this.secondaryChargingCollectionFunctionName = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TExtension }
     *     
     */
    public TExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExtension }
     *     
     */
    public void setExtension(TExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
