//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for tCSLocationInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCSLocationInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LocationNumber" type="{}tLocationNumber" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="CellGlobalId" type="{}tCellGlobalId" minOccurs="0"/>
 *           &lt;element name="ServiceAreaId" type="{}tServiceAreaId" minOccurs="0"/>
 *           &lt;element name="LocationAreaId" type="{}tLocationAreaId" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="GeographicalInformation" type="{}tGeographicalInformation" minOccurs="0"/>
 *         &lt;element name="GeodeticInformation" type="{}tGeodeticInformation" minOccurs="0"/>
 *         &lt;element name="VLRNumber" type="{}tISDNAddress" minOccurs="0"/>
 *         &lt;element name="MSCNumber" type="{}tISDNAddress" minOccurs="0"/>
 *         &lt;element name="CurrentLocationRetrieved" type="{}tBool" minOccurs="0"/>
 *         &lt;element name="AgeOfLocationInformation" type="{}tAgeOfLocationInformation" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tCSLocationInformation-Extension" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCSLocationInformation", propOrder = {
    "locationNumber",
    "cellGlobalId",
    "serviceAreaId",
    "locationAreaId",
    "geographicalInformation",
    "geodeticInformation",
    "vlrNumber",
    "mscNumber",
    "currentLocationRetrieved",
    "ageOfLocationInformation",
    "extension",
    "any"
})
public class TCSLocationInformation {

    @XmlElement(name = "LocationNumber")
    protected String locationNumber;
    @XmlElement(name = "CellGlobalId")
    protected String cellGlobalId;
    @XmlElement(name = "ServiceAreaId")
    protected String serviceAreaId;
    @XmlElement(name = "LocationAreaId")
    protected String locationAreaId;
    @XmlElement(name = "GeographicalInformation")
    protected String geographicalInformation;
    @XmlElement(name = "GeodeticInformation")
    protected String geodeticInformation;
    @XmlElement(name = "VLRNumber")
    protected TISDNAddress vlrNumber;
    @XmlElement(name = "MSCNumber")
    protected TISDNAddress mscNumber;
    @XmlElement(name = "CurrentLocationRetrieved")
    protected Boolean currentLocationRetrieved;
    @XmlElement(name = "AgeOfLocationInformation")
    protected Integer ageOfLocationInformation;
    @XmlElement(name = "Extension")
    protected TCSLocationInformationExtension extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the locationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationNumber() {
        return locationNumber;
    }

    /**
     * Sets the value of the locationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationNumber(String value) {
        this.locationNumber = value;
    }

    /**
     * Gets the value of the cellGlobalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellGlobalId() {
        return cellGlobalId;
    }

    /**
     * Sets the value of the cellGlobalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellGlobalId(String value) {
        this.cellGlobalId = value;
    }

    /**
     * Gets the value of the serviceAreaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceAreaId() {
        return serviceAreaId;
    }

    /**
     * Sets the value of the serviceAreaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceAreaId(String value) {
        this.serviceAreaId = value;
    }

    /**
     * Gets the value of the locationAreaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationAreaId() {
        return locationAreaId;
    }

    /**
     * Sets the value of the locationAreaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationAreaId(String value) {
        this.locationAreaId = value;
    }

    /**
     * Gets the value of the geographicalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeographicalInformation() {
        return geographicalInformation;
    }

    /**
     * Sets the value of the geographicalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeographicalInformation(String value) {
        this.geographicalInformation = value;
    }

    /**
     * Gets the value of the geodeticInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeodeticInformation() {
        return geodeticInformation;
    }

    /**
     * Sets the value of the geodeticInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeodeticInformation(String value) {
        this.geodeticInformation = value;
    }

    /**
     * Gets the value of the vlrNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TISDNAddress }
     *     
     */
    public TISDNAddress getVLRNumber() {
        return vlrNumber;
    }

    /**
     * Sets the value of the vlrNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TISDNAddress }
     *     
     */
    public void setVLRNumber(TISDNAddress value) {
        this.vlrNumber = value;
    }

    /**
     * Gets the value of the mscNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TISDNAddress }
     *     
     */
    public TISDNAddress getMSCNumber() {
        return mscNumber;
    }

    /**
     * Sets the value of the mscNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TISDNAddress }
     *     
     */
    public void setMSCNumber(TISDNAddress value) {
        this.mscNumber = value;
    }

    /**
     * Gets the value of the currentLocationRetrieved property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCurrentLocationRetrieved() {
        return currentLocationRetrieved;
    }

    /**
     * Sets the value of the currentLocationRetrieved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCurrentLocationRetrieved(Boolean value) {
        this.currentLocationRetrieved = value;
    }

    /**
     * Gets the value of the ageOfLocationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAgeOfLocationInformation() {
        return ageOfLocationInformation;
    }

    /**
     * Sets the value of the ageOfLocationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAgeOfLocationInformation(Integer value) {
        this.ageOfLocationInformation = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TCSLocationInformationExtension }
     *     
     */
    public TCSLocationInformationExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCSLocationInformationExtension }
     *     
     */
    public void setExtension(TCSLocationInformationExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
