//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDSAI complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDSAI">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DSAI-Tag" type="{}tDSAI-Tag"/>
 *         &lt;element name="DSAI-Value" type="{}tDSAI-Value"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDSAI", propOrder = {
    "dsaiTag",
    "dsaiValue"
})
public class TDSAI {

    @XmlElement(name = "DSAI-Tag", required = true)
    protected String dsaiTag;
    @XmlElement(name = "DSAI-Value")
    protected short dsaiValue;

    /**
     * Gets the value of the dsaiTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSAITag() {
        return dsaiTag;
    }

    /**
     * Sets the value of the dsaiTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSAITag(String value) {
        this.dsaiTag = value;
    }

    /**
     * Gets the value of the dsaiValue property.
     * 
     */
    public short getDSAIValue() {
        return dsaiValue;
    }

    /**
     * Sets the value of the dsaiValue property.
     * 
     */
    public void setDSAIValue(short value) {
        this.dsaiValue = value;
    }

}
