//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for tEPSLocationInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEPSLocationInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="E-UTRANCellGlobalId" type="{}tE-UTRANCellGlobalId" minOccurs="0"/>
 *         &lt;element name="TrackingAreaId" type="{}tTrackingAreaId" minOccurs="0"/>
 *         &lt;element name="GeographicalInformation" type="{}tGeographicalInformation" minOccurs="0"/>
 *         &lt;element name="GeodeticInformation" type="{}tGeodeticInformation" minOccurs="0"/>
 *         &lt;element name="MMEName" type="{}tString" minOccurs="0"/>
 *         &lt;element name="CurrentLocationRetrieved" type="{}tBool" minOccurs="0"/>
 *         &lt;element name="AgeOfLocationInformation" type="{}tAgeOfLocationInformation" minOccurs="0"/>
 *         &lt;element name="UserCSGInformation" type="{}tUserCSGInformation" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tEPSLocationInformation-Extension" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEPSLocationInformation", propOrder = {
    "eutranCellGlobalId",
    "trackingAreaId",
    "geographicalInformation",
    "geodeticInformation",
    "mmeName",
    "currentLocationRetrieved",
    "ageOfLocationInformation",
    "userCSGInformation",
    "extension",
    "any"
})
public class TEPSLocationInformation {

    @XmlElement(name = "E-UTRANCellGlobalId")
    protected String eutranCellGlobalId;
    @XmlElement(name = "TrackingAreaId")
    protected String trackingAreaId;
    @XmlElement(name = "GeographicalInformation")
    protected String geographicalInformation;
    @XmlElement(name = "GeodeticInformation")
    protected String geodeticInformation;
    @XmlElement(name = "MMEName")
    protected String mmeName;
    @XmlElement(name = "CurrentLocationRetrieved")
    protected Boolean currentLocationRetrieved;
    @XmlElement(name = "AgeOfLocationInformation")
    protected Integer ageOfLocationInformation;
    @XmlElement(name = "UserCSGInformation")
    protected TUserCSGInformation userCSGInformation;
    @XmlElement(name = "Extension")
    protected TEPSLocationInformationExtension extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the eutranCellGlobalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUTRANCellGlobalId() {
        return eutranCellGlobalId;
    }

    /**
     * Sets the value of the eutranCellGlobalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUTRANCellGlobalId(String value) {
        this.eutranCellGlobalId = value;
    }

    /**
     * Gets the value of the trackingAreaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingAreaId() {
        return trackingAreaId;
    }

    /**
     * Sets the value of the trackingAreaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingAreaId(String value) {
        this.trackingAreaId = value;
    }

    /**
     * Gets the value of the geographicalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeographicalInformation() {
        return geographicalInformation;
    }

    /**
     * Sets the value of the geographicalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeographicalInformation(String value) {
        this.geographicalInformation = value;
    }

    /**
     * Gets the value of the geodeticInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeodeticInformation() {
        return geodeticInformation;
    }

    /**
     * Sets the value of the geodeticInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeodeticInformation(String value) {
        this.geodeticInformation = value;
    }

    /**
     * Gets the value of the mmeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMMEName() {
        return mmeName;
    }

    /**
     * Sets the value of the mmeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMMEName(String value) {
        this.mmeName = value;
    }

    /**
     * Gets the value of the currentLocationRetrieved property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCurrentLocationRetrieved() {
        return currentLocationRetrieved;
    }

    /**
     * Sets the value of the currentLocationRetrieved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCurrentLocationRetrieved(Boolean value) {
        this.currentLocationRetrieved = value;
    }

    /**
     * Gets the value of the ageOfLocationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAgeOfLocationInformation() {
        return ageOfLocationInformation;
    }

    /**
     * Sets the value of the ageOfLocationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAgeOfLocationInformation(Integer value) {
        this.ageOfLocationInformation = value;
    }

    /**
     * Gets the value of the userCSGInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TUserCSGInformation }
     *     
     */
    public TUserCSGInformation getUserCSGInformation() {
        return userCSGInformation;
    }

    /**
     * Sets the value of the userCSGInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUserCSGInformation }
     *     
     */
    public void setUserCSGInformation(TUserCSGInformation value) {
        this.userCSGInformation = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TEPSLocationInformationExtension }
     *     
     */
    public TEPSLocationInformationExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEPSLocationInformationExtension }
     *     
     */
    public void setExtension(TEPSLocationInformationExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
