//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tExtendedPriority complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tExtendedPriority">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PriorityNamespace" type="{}tPriorityNamespace"/>
 *         &lt;element name="PriorityLevel" type="{}tPriorityLevel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tExtendedPriority", propOrder = {
    "priorityNamespace",
    "priorityLevel"
})
public class TExtendedPriority {

    @XmlElement(name = "PriorityNamespace", required = true)
    protected String priorityNamespace;
    @XmlElement(name = "PriorityLevel", required = true)
    protected String priorityLevel;

    /**
     * Gets the value of the priorityNamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorityNamespace() {
        return priorityNamespace;
    }

    /**
     * Sets the value of the priorityNamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorityNamespace(String value) {
        this.priorityNamespace = value;
    }

    /**
     * Gets the value of the priorityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorityLevel() {
        return priorityLevel;
    }

    /**
     * Sets the value of the priorityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorityLevel(String value) {
        this.priorityLevel = value;
    }

}
