//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tPSLocationInformation-Extension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPSLocationInformation-Extension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserCSGInformation" type="{}tUserCSGInformation" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tPSLocationInformation-Extension2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPSLocationInformation-Extension", propOrder = {
    "userCSGInformation",
    "extension"
})
public class TPSLocationInformationExtension {

    @XmlElement(name = "UserCSGInformation")
    protected TUserCSGInformation userCSGInformation;
    @XmlElement(name = "Extension")
    protected TPSLocationInformationExtension2 extension;

    /**
     * Gets the value of the userCSGInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TUserCSGInformation }
     *     
     */
    public TUserCSGInformation getUserCSGInformation() {
        return userCSGInformation;
    }

    /**
     * Sets the value of the userCSGInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUserCSGInformation }
     *     
     */
    public void setUserCSGInformation(TUserCSGInformation value) {
        this.userCSGInformation = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TPSLocationInformationExtension2 }
     *     
     */
    public TPSLocationInformationExtension2 getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPSLocationInformationExtension2 }
     *     
     */
    public void setExtension(TPSLocationInformationExtension2 value) {
        this.extension = value;
    }

}
