//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tPSLocationInformation-Extension2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPSLocationInformation-Extension2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VisitedPLMNID" type="{}tVisitedPLMNID" minOccurs="0"/>
 *         &lt;element name="LocalTimeZone" type="{}tLocalTimeZone" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tExtension" minOccurs="0"/>
 *         &lt;element name="RATtype" type="{}tRATtype" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPSLocationInformation-Extension2", propOrder = {
    "visitedPLMNID",
    "localTimeZone",
    "extension",
    "raTtype"
})
public class TPSLocationInformationExtension2 {

    @XmlElement(name = "VisitedPLMNID")
    protected String visitedPLMNID;
    @XmlElement(name = "LocalTimeZone")
    protected TLocalTimeZone localTimeZone;
    @XmlElement(name = "Extension")
    protected TExtension extension;
    @XmlElement(name = "RATtype")
    protected Integer raTtype;

    /**
     * Gets the value of the visitedPLMNID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitedPLMNID() {
        return visitedPLMNID;
    }

    /**
     * Sets the value of the visitedPLMNID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitedPLMNID(String value) {
        this.visitedPLMNID = value;
    }

    /**
     * Gets the value of the localTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link TLocalTimeZone }
     *     
     */
    public TLocalTimeZone getLocalTimeZone() {
        return localTimeZone;
    }

    /**
     * Sets the value of the localTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLocalTimeZone }
     *     
     */
    public void setLocalTimeZone(TLocalTimeZone value) {
        this.localTimeZone = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TExtension }
     *     
     */
    public TExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExtension }
     *     
     */
    public void setExtension(TExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the raTtype property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRATtype() {
        return raTtype;
    }

    /**
     * Sets the value of the raTtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRATtype(Integer value) {
        this.raTtype = value;
    }

}
