//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for tSePoTri complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSePoTri">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConditionNegated" type="{}tBool" minOccurs="0"/>
 *         &lt;element name="Group" type="{}tGroupID" maxOccurs="unbounded"/>
 *         &lt;choice>
 *           &lt;element name="RequestURI" type="{}tString"/>
 *           &lt;element name="Method" type="{}tString"/>
 *           &lt;element name="SIPHeader" type="{}tHeader"/>
 *           &lt;element name="SessionCase" type="{}tDirectionOfRequest"/>
 *           &lt;element name="SessionDescription" type="{}tSessionDescription"/>
 *         &lt;/choice>
 *         &lt;element name="Extension" type="{}tSePoTriExtension" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSePoTri", propOrder = {
    "conditionNegated",
    "group",
    "requestURI",
    "method",
    "sipHeader",
    "sessionCase",
    "sessionDescription",
    "extension",
    "any"
})
public class TSePoTri {

    @XmlElement(name = "ConditionNegated")
    protected Boolean conditionNegated;
    @XmlElement(name = "Group", type = Integer.class)
    protected List<Integer> group;
    @XmlElement(name = "RequestURI")
    protected String requestURI;
    @XmlElement(name = "Method")
    protected String method;
    @XmlElement(name = "SIPHeader")
    protected THeader sipHeader;
    @XmlElement(name = "SessionCase")
    protected Short sessionCase;
    @XmlElement(name = "SessionDescription")
    protected TSessionDescription sessionDescription;
    @XmlElement(name = "Extension")
    protected TSePoTriExtension extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the conditionNegated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isConditionNegated() {
        return conditionNegated;
    }

    /**
     * Sets the value of the conditionNegated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConditionNegated(Boolean value) {
        this.conditionNegated = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getGroup() {
        if (group == null) {
            group = new ArrayList<Integer>();
        }
        return this.group;
    }

    /**
     * Gets the value of the requestURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestURI() {
        return requestURI;
    }

    /**
     * Sets the value of the requestURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestURI(String value) {
        this.requestURI = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the sipHeader property.
     * 
     * @return
     *     possible object is
     *     {@link THeader }
     *     
     */
    public THeader getSIPHeader() {
        return sipHeader;
    }

    /**
     * Sets the value of the sipHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link THeader }
     *     
     */
    public void setSIPHeader(THeader value) {
        this.sipHeader = value;
    }

    /**
     * Gets the value of the sessionCase property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSessionCase() {
        return sessionCase;
    }

    /**
     * Sets the value of the sessionCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSessionCase(Short value) {
        this.sessionCase = value;
    }

    /**
     * Gets the value of the sessionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link TSessionDescription }
     *     
     */
    public TSessionDescription getSessionDescription() {
        return sessionDescription;
    }

    /**
     * Sets the value of the sessionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSessionDescription }
     *     
     */
    public void setSessionDescription(TSessionDescription value) {
        this.sessionDescription = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TSePoTriExtension }
     *     
     */
    public TSePoTriExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSePoTriExtension }
     *     
     */
    public void setExtension(TSePoTriExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
