//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;


/**
 * <p>Java class for tSh-Data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSh-Data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PublicIdentifiers" type="{}tPublicIdentity" minOccurs="0"/>
 *         &lt;element name="RepositoryData" type="{}tTransparentData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Sh-IMS-Data" type="{}tShIMSData" minOccurs="0"/>
 *         &lt;element name="CSLocationInformation" type="{}tCSLocationInformation" minOccurs="0"/>
 *         &lt;element name="PSLocationInformation" type="{}tPSLocationInformation" minOccurs="0"/>
 *         &lt;element name="CSUserState" type="{}tCSUserState" minOccurs="0"/>
 *         &lt;element name="PSUserState" type="{}tPSUserState" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tSh-Data-Extension" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSh-Data", propOrder = {
    "publicIdentifiers",
    "repositoryData",
    "shIMSData",
    "csLocationInformation",
    "psLocationInformation",
    "csUserState",
    "psUserState",
    "extension",
    "any"
})
@XmlRootElement(name = "Sh-Data")   // Added 2016
public class TShData {

    @XmlElement(name = "PublicIdentifiers")
    protected TPublicIdentity publicIdentifiers;
    @XmlElement(name = "RepositoryData")
    protected List<TTransparentData> repositoryData;
    @XmlElement(name = "Sh-IMS-Data")
    protected TShIMSData shIMSData;
    @XmlElement(name = "CSLocationInformation")
    protected TCSLocationInformation csLocationInformation;
    @XmlElement(name = "PSLocationInformation")
    protected TPSLocationInformation psLocationInformation;
    @XmlElement(name = "CSUserState")
    protected Short csUserState;
    @XmlElement(name = "PSUserState")
    protected Short psUserState;
    @XmlElement(name = "Extension")
    protected TShDataExtension extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the publicIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link TPublicIdentity }
     *     
     */
    public TPublicIdentity getPublicIdentifiers() {
        return publicIdentifiers;
    }

    /**
     * Sets the value of the publicIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublicIdentity }
     *     
     */
    public void setPublicIdentifiers(TPublicIdentity value) {
        this.publicIdentifiers = value;
    }

    /**
     * Gets the value of the repositoryData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repositoryData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepositoryData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTransparentData }
     * 
     * 
     */
    public List<TTransparentData> getRepositoryData() {
        if (repositoryData == null) {
            repositoryData = new ArrayList<TTransparentData>();
        }
        return this.repositoryData;
    }

    /**
     * Gets the value of the shIMSData property.
     * 
     * @return
     *     possible object is
     *     {@link TShIMSData }
     *     
     */
    public TShIMSData getShIMSData() {
        return shIMSData;
    }

    /**
     * Sets the value of the shIMSData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TShIMSData }
     *     
     */
    public void setShIMSData(TShIMSData value) {
        this.shIMSData = value;
    }

    /**
     * Gets the value of the csLocationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TCSLocationInformation }
     *     
     */
    public TCSLocationInformation getCSLocationInformation() {
        return csLocationInformation;
    }

    /**
     * Sets the value of the csLocationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCSLocationInformation }
     *     
     */
    public void setCSLocationInformation(TCSLocationInformation value) {
        this.csLocationInformation = value;
    }

    /**
     * Gets the value of the psLocationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TPSLocationInformation }
     *     
     */
    public TPSLocationInformation getPSLocationInformation() {
        return psLocationInformation;
    }

    /**
     * Sets the value of the psLocationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPSLocationInformation }
     *     
     */
    public void setPSLocationInformation(TPSLocationInformation value) {
        this.psLocationInformation = value;
    }

    /**
     * Gets the value of the csUserState property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCSUserState() {
        return csUserState;
    }

    /**
     * Sets the value of the csUserState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCSUserState(Short value) {
        this.csUserState = value;
    }

    /**
     * Gets the value of the psUserState property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPSUserState() {
        return psUserState;
    }

    /**
     * Sets the value of the psUserState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPSUserState(Short value) {
        this.psUserState = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TShDataExtension }
     *     
     */
    public TShDataExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TShDataExtension }
     *     
     */
    public void setExtension(TShDataExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
