//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for tSh-Data-Extension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSh-Data-Extension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegisteredIdentities" type="{}tPublicIdentity" minOccurs="0"/>
 *         &lt;element name="ImplicitIdentities" type="{}tPublicIdentity" minOccurs="0"/>
 *         &lt;element name="AllIdentities" type="{}tPublicIdentity" minOccurs="0"/>
 *         &lt;element name="AliasIdentities" type="{}tPublicIdentity" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tSh-Data-Extension2" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSh-Data-Extension", propOrder = {
    "registeredIdentities",
    "implicitIdentities",
    "allIdentities",
    "aliasIdentities",
    "extension",
    "any"
})
public class TShDataExtension {

    @XmlElement(name = "RegisteredIdentities")
    protected TPublicIdentity registeredIdentities;
    @XmlElement(name = "ImplicitIdentities")
    protected TPublicIdentity implicitIdentities;
    @XmlElement(name = "AllIdentities")
    protected TPublicIdentity allIdentities;
    @XmlElement(name = "AliasIdentities")
    protected TPublicIdentity aliasIdentities;
    @XmlElement(name = "Extension")
    protected TShDataExtension2 extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the registeredIdentities property.
     * 
     * @return
     *     possible object is
     *     {@link TPublicIdentity }
     *     
     */
    public TPublicIdentity getRegisteredIdentities() {
        return registeredIdentities;
    }

    /**
     * Sets the value of the registeredIdentities property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublicIdentity }
     *     
     */
    public void setRegisteredIdentities(TPublicIdentity value) {
        this.registeredIdentities = value;
    }

    /**
     * Gets the value of the implicitIdentities property.
     * 
     * @return
     *     possible object is
     *     {@link TPublicIdentity }
     *     
     */
    public TPublicIdentity getImplicitIdentities() {
        return implicitIdentities;
    }

    /**
     * Sets the value of the implicitIdentities property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublicIdentity }
     *     
     */
    public void setImplicitIdentities(TPublicIdentity value) {
        this.implicitIdentities = value;
    }

    /**
     * Gets the value of the allIdentities property.
     * 
     * @return
     *     possible object is
     *     {@link TPublicIdentity }
     *     
     */
    public TPublicIdentity getAllIdentities() {
        return allIdentities;
    }

    /**
     * Sets the value of the allIdentities property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublicIdentity }
     *     
     */
    public void setAllIdentities(TPublicIdentity value) {
        this.allIdentities = value;
    }

    /**
     * Gets the value of the aliasIdentities property.
     * 
     * @return
     *     possible object is
     *     {@link TPublicIdentity }
     *     
     */
    public TPublicIdentity getAliasIdentities() {
        return aliasIdentities;
    }

    /**
     * Sets the value of the aliasIdentities property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPublicIdentity }
     *     
     */
    public void setAliasIdentities(TPublicIdentity value) {
        this.aliasIdentities = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TShDataExtension2 }
     *     
     */
    public TShDataExtension2 getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TShDataExtension2 }
     *     
     */
    public void setExtension(TShDataExtension2 value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
