//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tShIMSDataExtension3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tShIMSDataExtension3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceLevelTraceInfo" type="{}tServiceLevelTraceInfo" minOccurs="0"/>
 *         &lt;element name="IPv4Address" type="{}tIPv4Address" minOccurs="0"/>
 *         &lt;element name="IPv6Prefix" type="{}tIPv6Prefix" minOccurs="0"/>
 *         &lt;element name="IPv6InterfaceIdentifier" type="{}tIPv6InterfaceIdentifier" minOccurs="0"/>
 *         &lt;element name="ServicePriorityLevel" type="{}tServicePriorityLevel" minOccurs="0"/>
 *         &lt;element name="UEReachabilityForIP" type="{}tUEReachabilityForIP" minOccurs="0"/>
 *         &lt;element name="SMSRegistrationInfo" type="{}tSMSRegistrationInfo" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tShIMSDataExtension4" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tShIMSDataExtension3", propOrder = {
    "serviceLevelTraceInfo",
    "iPv4Address",
    "iPv6Prefix",
    "iPv6InterfaceIdentifier",
    "servicePriorityLevel",
    "ueReachabilityForIP",
    "smsRegistrationInfo",
    "extension"
})
public class TShIMSDataExtension3 {

    @XmlElement(name = "ServiceLevelTraceInfo")
    protected String serviceLevelTraceInfo;
    @XmlElement(name = "IPv4Address")
    protected String iPv4Address;
    @XmlElement(name = "IPv6Prefix")
    protected String iPv6Prefix;
    @XmlElement(name = "IPv6InterfaceIdentifier")
    protected String iPv6InterfaceIdentifier;
    @XmlElement(name = "ServicePriorityLevel")
    protected Short servicePriorityLevel;
    @XmlElement(name = "UEReachabilityForIP")
    protected TUEReachabilityForIP ueReachabilityForIP;
    @XmlElement(name = "SMSRegistrationInfo")
    protected TSMSRegistrationInfo smsRegistrationInfo;
    @XmlElement(name = "Extension")
    protected TShIMSDataExtension4 extension;

    /**
     * Gets the value of the serviceLevelTraceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLevelTraceInfo() {
        return serviceLevelTraceInfo;
    }

    /**
     * Sets the value of the serviceLevelTraceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLevelTraceInfo(String value) {
        this.serviceLevelTraceInfo = value;
    }

    /**
     * Gets the value of the iPv4Address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPv4Address() {
        return iPv4Address;
    }

    /**
     * Sets the value of the iPv4Address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPv4Address(String value) {
        this.iPv4Address = value;
    }

    /**
     * Gets the value of the iPv6Prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPv6Prefix() {
        return iPv6Prefix;
    }

    /**
     * Sets the value of the iPv6Prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPv6Prefix(String value) {
        this.iPv6Prefix = value;
    }

    /**
     * Gets the value of the iPv6InterfaceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPv6InterfaceIdentifier() {
        return iPv6InterfaceIdentifier;
    }

    /**
     * Sets the value of the iPv6InterfaceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPv6InterfaceIdentifier(String value) {
        this.iPv6InterfaceIdentifier = value;
    }

    /**
     * Gets the value of the servicePriorityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getServicePriorityLevel() {
        return servicePriorityLevel;
    }

    /**
     * Sets the value of the servicePriorityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setServicePriorityLevel(Short value) {
        this.servicePriorityLevel = value;
    }

    /**
     * Gets the value of the ueReachabilityForIP property.
     * 
     * @return
     *     possible object is
     *     {@link TUEReachabilityForIP }
     *     
     */
    public TUEReachabilityForIP getUEReachabilityForIP() {
        return ueReachabilityForIP;
    }

    /**
     * Sets the value of the ueReachabilityForIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUEReachabilityForIP }
     *     
     */
    public void setUEReachabilityForIP(TUEReachabilityForIP value) {
        this.ueReachabilityForIP = value;
    }

    /**
     * Gets the value of the smsRegistrationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TSMSRegistrationInfo }
     *     
     */
    public TSMSRegistrationInfo getSMSRegistrationInfo() {
        return smsRegistrationInfo;
    }

    /**
     * Sets the value of the smsRegistrationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSMSRegistrationInfo }
     *     
     */
    public void setSMSRegistrationInfo(TSMSRegistrationInfo value) {
        this.smsRegistrationInfo = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TShIMSDataExtension4 }
     *     
     */
    public TShIMSDataExtension4 getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TShIMSDataExtension4 }
     *     
     */
    public void setExtension(TShIMSDataExtension4 value) {
        this.extension = value;
    }

}
