//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tShIMSDataExtension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tShIMSDataExtension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PSIActivation" type="{}tPSIActivation" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tShIMSDataExtension2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tShIMSDataExtension", propOrder = {
    "psiActivation",
    "extension"
})
public class TShIMSDataExtension {

    @XmlElement(name = "PSIActivation")
    protected Short psiActivation;
    @XmlElement(name = "Extension")
    protected TShIMSDataExtension2 extension;

    /**
     * Gets the value of the psiActivation property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPSIActivation() {
        return psiActivation;
    }

    /**
     * Sets the value of the psiActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPSIActivation(Short value) {
        this.psiActivation = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TShIMSDataExtension2 }
     *     
     */
    public TShIMSDataExtension2 getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TShIMSDataExtension2 }
     *     
     */
    public void setExtension(TShIMSDataExtension2 value) {
        this.extension = value;
    }

}
