//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for tShIMSData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tShIMSData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SCSCFName" type="{}tSIP_URL" minOccurs="0"/>
 *         &lt;element name="IFCs" type="{}tIFCs" minOccurs="0"/>
 *         &lt;element name="IMSUserState" type="{}tIMSUserState" minOccurs="0"/>
 *         &lt;element name="ChargingInformation" type="{}tChargingInformation" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tShIMSDataExtension" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tShIMSData", propOrder = {
    "scscfName",
    "ifCs",
    "imsUserState",
    "chargingInformation",
    "extension",
    "any"
})
public class TShIMSData {

    @XmlElement(name = "SCSCFName")
    protected String scscfName;
    @XmlElement(name = "IFCs")
    protected TIFCs ifCs;
    @XmlElement(name = "IMSUserState")
    protected Short imsUserState;
    @XmlElement(name = "ChargingInformation")
    protected TChargingInformation chargingInformation;
    @XmlElement(name = "Extension")
    protected TShIMSDataExtension extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the scscfName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCSCFName() {
        return scscfName;
    }

    /**
     * Sets the value of the scscfName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCSCFName(String value) {
        this.scscfName = value;
    }

    /**
     * Gets the value of the ifCs property.
     * 
     * @return
     *     possible object is
     *     {@link TIFCs }
     *     
     */
    public TIFCs getIFCs() {
        return ifCs;
    }

    /**
     * Sets the value of the ifCs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIFCs }
     *     
     */
    public void setIFCs(TIFCs value) {
        this.ifCs = value;
    }

    /**
     * Gets the value of the imsUserState property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getIMSUserState() {
        return imsUserState;
    }

    /**
     * Sets the value of the imsUserState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setIMSUserState(Short value) {
        this.imsUserState = value;
    }

    /**
     * Gets the value of the chargingInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TChargingInformation }
     *     
     */
    public TChargingInformation getChargingInformation() {
        return chargingInformation;
    }

    /**
     * Sets the value of the chargingInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TChargingInformation }
     *     
     */
    public void setChargingInformation(TChargingInformation value) {
        this.chargingInformation = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TShIMSDataExtension }
     *     
     */
    public TShIMSDataExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TShIMSDataExtension }
     *     
     */
    public void setExtension(TShIMSDataExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
