//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for tTWANLocationInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTWANLocationInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TWAN-SSID" type="{}tTWAN-SSID" minOccurs="0"/>
 *         &lt;element name="TWAN-BSSID" type="{}tTWAN-BSSID" minOccurs="0"/>
 *         &lt;element name="TWAN-PLMNID" type="{}tVisitedPLMNID" minOccurs="0"/>
 *         &lt;element name="CivicAddress" type="{}tCivicAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TWANOperatorName" type="{}tTWANOperatorName" minOccurs="0"/>
 *         &lt;element name="LocalTimeZone" type="{}tLocalTimeZone" minOccurs="0"/>
 *         &lt;element name="LogicalAccessID" type="{}tLogicalAccessID" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tExtension" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTWANLocationInformation", propOrder = {
    "twanssid",
    "twanbssid",
    "twanplmnid",
    "civicAddress",
    "twanOperatorName",
    "localTimeZone",
    "logicalAccessID",
    "extension",
    "any"
})
public class TTWANLocationInformation {

    @XmlElement(name = "TWAN-SSID")
    protected String twanssid;
    @XmlElement(name = "TWAN-BSSID")
    protected String twanbssid;
    @XmlElement(name = "TWAN-PLMNID")
    protected String twanplmnid;
    @XmlElement(name = "CivicAddress")
    protected List<byte[]> civicAddress;
    @XmlElement(name = "TWANOperatorName")
    protected String twanOperatorName;
    @XmlElement(name = "LocalTimeZone")
    protected TLocalTimeZone localTimeZone;
    @XmlElement(name = "LogicalAccessID")
    protected String logicalAccessID;
    @XmlElement(name = "Extension")
    protected TExtension extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the twanssid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTWANSSID() {
        return twanssid;
    }

    /**
     * Sets the value of the twanssid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTWANSSID(String value) {
        this.twanssid = value;
    }

    /**
     * Gets the value of the twanbssid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTWANBSSID() {
        return twanbssid;
    }

    /**
     * Sets the value of the twanbssid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTWANBSSID(String value) {
        this.twanbssid = value;
    }

    /**
     * Gets the value of the twanplmnid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTWANPLMNID() {
        return twanplmnid;
    }

    /**
     * Sets the value of the twanplmnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTWANPLMNID(String value) {
        this.twanplmnid = value;
    }

    /**
     * Gets the value of the civicAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the civicAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCivicAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * byte[]
     * 
     */
    public List<byte[]> getCivicAddress() {
        if (civicAddress == null) {
            civicAddress = new ArrayList<byte[]>();
        }
        return this.civicAddress;
    }

    /**
     * Gets the value of the twanOperatorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTWANOperatorName() {
        return twanOperatorName;
    }

    /**
     * Sets the value of the twanOperatorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTWANOperatorName(String value) {
        this.twanOperatorName = value;
    }

    /**
     * Gets the value of the localTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link TLocalTimeZone }
     *     
     */
    public TLocalTimeZone getLocalTimeZone() {
        return localTimeZone;
    }

    /**
     * Sets the value of the localTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLocalTimeZone }
     *     
     */
    public void setLocalTimeZone(TLocalTimeZone value) {
        this.localTimeZone = value;
    }

    /**
     * Gets the value of the logicalAccessID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalAccessID() {
        return logicalAccessID;
    }

    /**
     * Sets the value of the logicalAccessID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalAccessID(String value) {
        this.logicalAccessID = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TExtension }
     *     
     */
    public TExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExtension }
     *     
     */
    public void setExtension(TExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
