//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:47:19 PM SAST 
//


package com.inted.as.hss.fe.sh.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tUserCSGInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tUserCSGInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CSGId" type="{}tCSGId" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Extension" type="{}tUserCSGInformation-Extension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tUserCSGInformation", propOrder = {
    "csgId",
    "extension"
})
public class TUserCSGInformation {

    @XmlElement(name = "CSGId")
    protected List<String> csgId;
    @XmlElement(name = "Extension")
    protected TUserCSGInformationExtension extension;

    /**
     * Gets the value of the csgId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the csgId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCSGId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCSGId() {
        if (csgId == null) {
            csgId = new ArrayList<String>();
        }
        return this.csgId;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TUserCSGInformationExtension }
     *     
     */
    public TUserCSGInformationExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUserCSGInformationExtension }
     *     
     */
    public void setExtension(TUserCSGInformationExtension value) {
        this.extension = value;
    }

}
